# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GainzTracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(958, 672)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Date = QtWidgets.QDateEdit(Dialog)
        self.Date.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.Date.setObjectName("Date")
        self.verticalLayout.addWidget(self.Date)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Workout = QtWidgets.QComboBox(Dialog)
        self.Workout.setObjectName("Workout")
        self.Workout.addItem("")
        self.Workout.addItem("")
        self.Workout.addItem("")
        self.Workout.addItem("")
        self.Workout.addItem("")
        self.Workout.addItem("")
        self.Workout.addItem("")
        self.verticalLayout.addWidget(self.Workout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Creatine = QtWidgets.QLineEdit(Dialog)
        self.Creatine.setText("")
        self.Creatine.setObjectName("Creatine")
        self.verticalLayout.addWidget(self.Creatine)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.Weight = QtWidgets.QLineEdit(Dialog)
        self.Weight.setText("")
        self.Weight.setObjectName("Weight")
        self.verticalLayout.addWidget(self.Weight)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose the Date "))
        self.label_2.setText(_translate("Dialog", "Choose the workout"))
        self.Workout.setItemText(0, _translate("Dialog", "Leg Day"))
        self.Workout.setItemText(1, _translate("Dialog", "Push Day"))
        self.Workout.setItemText(2, _translate("Dialog", "Pull Day "))
        self.Workout.setItemText(3, _translate("Dialog", "Upper Body "))
        self.Workout.setItemText(4, _translate("Dialog", "LowerBody"))
        self.Workout.setItemText(5, _translate("Dialog", "Cardio"))
        self.Workout.setItemText(6, _translate("Dialog", "Random Exercices"))
        self.label_3.setText(_translate("Dialog", "Creatine Intake of the day "))
        self.label_4.setText(_translate("Dialog", "Weight "))
        self.pushButton.setText(_translate("Dialog", "Submit the Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
